var gfc_Dn=osapi,gfc_En="ceil";gfc_1[gfc_].share=gfc_3c(23,function(){gfc_6m();return gfc_d});gfc_Zf[gfc_].ceil=gfc_3c(19,function(){gfc_ua(this,gfc_j[gfc_En](this[gfc_o]));gfc_Oa(this,gfc_j[gfc_En](this[gfc_J]));return this});gfc_1[gfc_].Fi=gfc_3c(18,function(){var a=this.yd;a.valid?(this.d=this.vg(this.yd),this.Fh(a[gfc_Pb])):(this.yd=gfc_c,this.render(a.actions,a[gfc_Pb],a.params));this.ug()});gfc_1[gfc_].wf=gfc_3c(14,function(){return this.Eb.pop()});
gfc_1[gfc_].gi=gfc_3c(5,function(a,b,c){return a?c<b?[]:a[gfc_gb](gfc_j.min(b,a[gfc_m]),gfc_j.min(c,a[gfc_m])):[]});
var gfc_Fn=function(a){return a=gfc_g.friendconnect_serverBase+"/friendconnect/favicon?url="+escape(a)},gfc_7=function(a,b,c){this.Ea();this.Jq();var d=new gfc_O;d.set("members",{action:this.Rt,callback:this.Os});d.set("member-page",{action:this.Qt,callback:this.Ns});d.set("blocked-member-page",{action:this.Kt,callback:this.Js});d.set("profile-friends-page",{action:this.Wt,callback:this.Ss});d.set("sitesData",{action:this.du,callback:this.Ws});d.set("viewerFriends",{action:this.iu,callback:this.Ys});
d.set("profileData",{action:this.Vt,callback:this.Rs});d.set("blockUser",{action:this.Jt,callback:this.Is});d.set("unblockUser",{action:this.gu,callback:this.Xs});d.set("profileFriends",{action:this.Xt,callback:this.Ts});d.set("activityData",{action:this.Ff,callback:this.ld});d.set("sendFriendRequest",{action:this.cu,callback:this.Vs});d.set("sendFriendRequestResponse",{action:this.Nt,callback:this.Nl});d.set("deleteActivity",{action:this.Gf,callback:this.ld});d.set("requestAndProcessViewerNumWaitingMessages",
{action:this.ju,callback:this.$s});d.set("requestPromo",{action:this.Yt,callback:this.Us});this.hb=gfc_c;this.Aw=new gfc_dn("fc-members-options-menu",gfc_L(this.ks,this),gfc_L(this.js,this),gfc_L(this.ls,this),0,gfc_g.friendconnect_serverBase,this.f("ENDCAP_LINK_COLOR")||"0000cc",this.f("CONTENT_TEXT_COLOR")||"000000");this.ov=gfc_d;this.Ba=10;this.rf=15;this.Om=10;var e=gfc_Zg(gfc_Kg()),f=gfc_Gn;this.Xb=3;this.rc=8;this.km=gfc_c;this.oa=this.rc*this.Xb;this.slimTopCapHeight=19;this.tinyTopCapHeight=
8;this.isMessagingEnabled=a;this.isPromosEnabled=b;this.isSocialShareEnabled=c;this.numWaitingMessages=0;this.promoCode=-1;this.promoHtml=gfc_c;this.Pb=new gfc_$m;this.zh()&&(a=(a=this.f(f.FACE_SIZE))?gfc_ha(a):32,a+=6,this.Xb=gfc_j[gfc_nb]((e[gfc_o]-10)/a),e=340,e=this.f(f.HEIGHT),b=this.f(f.NUMBER_ROWS),f=27,b?(this.rc=gfc_ha(b),e=this.rc*a,this.km=e+f):e&&(e=gfc_ha(e)-96,this.rc=gfc_j.max(2,gfc_j[gfc_nb](e/a)),this.km=this.rc*a+f),this.oa=this.rc*this.Xb);gfc_1[gfc_A](this,d)};gfc_7.inherits(gfc_1);
gfc_Ea(gfc_7[gfc_],function(){gfc_7.i[gfc_C][gfc_A](this);gfc_Im("start");var a=gfc_e[gfc_n][gfc_Tb](),b=gfc_la();(a=b.profileId||a.profileId)?(b={},b[gfc_h[gfc_t][gfc_H].ID]=a,a=new gfc_h[gfc_t](b),this.render(["profileData","profileFriends","activityData"],"profile",{person:a})):(a=["members","viewerFriends"],this.isMessagingEnabled&&a[gfc_l]("requestAndProcessViewerNumWaitingMessages"),this.isPromosEnabled&&!this.Ib()&&a[gfc_l]("requestPromo"),this.render(a,"faces"))});gfc_7[gfc_].e={};
gfc_7[gfc_].Ea=function(){this.e.MSG_SITE_MEMBERS="Miembros";this.e.MSG_BE_THE_FIRST="\u00a1S\u00e9 el primero!";this.e.MSG_NO_SITE_MEMBERS="Todav\u00eda no hay miembros.";this.e.MSG_ALL_SITE_MEMBERS="Todos los miembros";this.e.MSG_ALL_BLOCKED_MEMBERS="Todos los miembros bloqueados";this.e.MSG_NO_BLOCKED_MEMBERS="No has bloqueado a ning\u00fan miembro.";this.e.MSG_YOUR_FRIENDS="Tus amigos";this.e.MSG_ALL_YOUR_FRIENDS="Todos tus amigos";this.e.MSG_JFJ="Participa y con\u00e9ctate con otros.";this.e.MSG_MANAGE=
"Administrar miembros";this.e.MSG_SETTINGS="Configuraci\u00f3n";this.e.MSG_OPTIONS="Opciones";this.e.MSG_INVITE="Invitar";this.e.MSG_MEMBERS_SHARE="Comparte esta p\u00e1gina";this.e.MSG_BACK="Atr\u00e1s";this.e.MSG_BACK_TO_TOP="Inicio";this.e.MSG_VIEW_MY_PROFILE="Ver mi perfil";this.e.MSG_ABOUT_ME="Acerca de m\u00ed";this.e.MSG_MORE="M\u00e1s \u00bb";this.e.MSG_SHOW_BLOCKED="Mostrar a los miembros bloqueados \u00bb";this.e.MSG_SHOW_ALL="\u00ab Mostrar a todos los miembros";this.e.MSG_INVITE_YOUR_FRIENDS=
"Invitar a tus amigos";this.e.MSG_LINK_IN_NETWORKS="Conectar tus redes sociales";this.e.MSG_ACTIVITIES="Actividades";this.e.MSG_ALL_ACTIVITIES="M\u00e1s actividades";this.e.MSG_DELETE_THIS="Suprimir";this.e.MSG_SITES="Sitios en los que participo";this.e.MSG_ALL_SITES="M\u00e1s sitios en los que participo";this.e.MSG_LINKS="Enlaces";this.e.MSG_ALL_LINKS="M\u00e1s enlaces";this.e.MSG_NO_ACTIVITIES="No hay actividades para mostrar.";this.e.MSG_ADD_AS_FRIEND="A\u00f1adir como amigo/a";this.e.MSG_SEND_MESSAGE=
"Enviar un mensaje";this.e.MSG_BLOCK_USER="Bloquear a este usuario";this.e.MSG_UNBLOCK_USER="Desbloquear a este usuario";this.e.MSG_USER_IS_ADMIN="Administrador";this.e.MSG_JOIN="Participar en este sitio";this.e.MSG_OR="o";this.e.MSG_SIGN_IN="Acceder";this.e.MSG_SIGN_OUT="Salir";this.e.MSG_PREVIOUS="\u00ab Anterior";this.e.MSG_NEXT="Siguiente \u00bb";this.e.MSG_NEWER="\u00ab M\u00e1s recientes";this.e.MSG_OLDER="Anteriores \u00bb";this.e.MSG_ACCEPT_ALL_FRIEND_REQUESTS="Aceptar todas";this.e.MSG_HELP_FRIENDREQUEST=
"Coincidir\u00e1s con tus amigos en todos los sitios de Google Friend Connect.";this.e.MSG_HELP_FRIENDINVITE="Una vez que se\u00e1is amigos, coincidir\u00e9is en todos los sitios de Google Friend Connect.";this.e.MSG_HELP_BLOCKMEMBER="Si bloqueas a un usuario, lo eliminar\u00e1s de la lista de miembros e impedir\u00e1s que interact\u00fae con los dem\u00e1s usuarios de tu sitio.";this.e.MSG_INVITATION="Invitaci\u00f3n:";this.e.MSG_SEND="Enviar";this.e.MSG_BLOCK="Bloquear";this.e.MSG_IGNORE="Ignorar";
this.e.MSG_CANCEL="Cancelar";this.e.MSG_SITE_SETTINGS="Configuraci\u00f3n del sitio";this.e.MSG_INVITE_FRIENDS="Invitar a amigos";this.e.MSG_ABOUT_FC="Acerca de Google Friend Connect";this.e.MSG_ALREADY_MEMBER="\u00bfYa eres miembro?";this.e.MSG_EDIT_PROFILE="Editar perfil"};gfc_7[gfc_].ra={};
gfc_7[gfc_].Jq=function(){this.ra.MSG_SITE_MEMBERS="Seguidores";this.ra.MSG_NO_SITE_MEMBERS="Todav\u00eda no hay seguidores.";this.ra.MSG_SHOW_BLOCKED="Mostrar seguidores bloqueados \u00bb";this.ra.MSG_SHOW_ALL="\u00ab Mostrar a todos los seguidores";this.ra.MSG_ALL_SITE_MEMBERS="Todos los seguidores";this.ra.MSG_ALL_BLOCKED_MEMBERS="Todos los seguidores bloqueados";this.ra.MSG_NO_BLOCKED_MEMBERS="No has bloqueado a ning\u00fan seguidor.";this.ra.MSG_LIKE_THIS_SITE="\u00bfTe gusta este blog?";this.ra.MSG_JOIN=
"Seguir";this.ra.MSG_BACK_TO_TOP="Miembros";this.ra.MSG_JFJ="Seguir y conectarte con tus amigos";this.ra.MSG_HELP_FRIENDREQUEST="Coincidir\u00e1s con tus amigos en los sitios de seguimiento de blogs y de Google Friend Connect.";this.ra.MSG_HELP_FRIENDINVITE="Una vez que se\u00e1is amigos, coincidir\u00e9is en los sitios de Seguimiento de blogs y de Google Friend Connect."};
gfc_7[gfc_].M=function(a,b){var c=gfc_b;if(b[gfc_D]&&b[gfc_D].person){var d={},e=b[gfc_D].person[gfc_Lb]()+" es tu amigo/a.";d.MSG_IS_FRIEND=e;e="Has invitado a "+(b[gfc_D].person[gfc_Lb]()+" a que sea tu amigo/a.");d.MSG_IS_INVITED=e;e="Amigos de "+b[gfc_D].person[gfc_Lb]();d.MSG_PROFILE_FRIENDS=e;e="Todos los amigos de "+b[gfc_D].person[gfc_Lb]();d.MSG_ALL_PROFILE_FRIENDS=e;for(var f in d)this.h(a,f,d[f])}b.invitedBy&&b.invitedBy[gfc_Lb]()&&(d=gfc_i[gfc_o]?gfc_i[gfc_o]:gfc_i[gfc_Ob][gfc_cb]+2,c=
(d-135)/8,d=(d-175)/8,c="Ver el perfil de "+gfc_wm(b.invitedBy[gfc_Lb](),c),d=gfc_wm(b.invitedBy[gfc_Lb](),d)+" te ha invitado a este sitio.",this.h(a,"MSG_VIEW_INVITER_PROFILE",c),this.h(a,"MSG_INVITED_YOU",d),this.ov=gfc_b,c=gfc_d);d="Hay "+(this.numWaitingMessages+" mensajes esper\u00e1ndote.");this.isMessagingEnabled&&0<this.numWaitingMessages&&(c=gfc_d,this.h(a,"showWaitingMessages",gfc_b),this.isMessagingEnabled&&(this.h(a,"MSG_NUM_WAITING_MESSAGES",d),this.h(a,"MSG_VIEW_AND_CONFIGURE_MESSAGING",
"Ver mensajes")));b.friendRequests&&(0<b.friendRequests[gfc_9a]()&&(c=gfc_d),d=1==b.friendRequests[gfc_9a]()?"Nueva solicitud de amistad \u00bb":"Nuevas solicitudes de amistad ("+(b.friendRequests[gfc_9a]()+") \u00bb"),this.h(a,"MSG_NEW_FRIEND_REQUESTS",d));if(this.hb){if(this.Wk(this.hb.themeId))for(f in this.ra)this.h(a,f,this.ra[f]);this.hb.signInPrompt&&this.h(a,"MSG_JOIN",this.hb.signInPrompt);this.hb.signOutPrompt&&this.h(a,"MSG_SIGN_OUT",this.hb.signOutPrompt)}this.h(a,"isViewerAdmin",b.isViewerAdmin);
this.h(a,"isMessagingEnabled",this.isMessagingEnabled);this.h(a,"acceptMessages",this.pn);this.h(a,"isViewingSelf",b.viewer&&b[gfc_D]&&b[gfc_D].person&&b.viewer[gfc_z]()==b[gfc_D].person[gfc_z]());d=gfc_d;if(b.owner&&(e=b.owner[gfc_I]("profileExtensions")))for(f in e)d=gfc_b;this.h(a,"communityHasProfile",d);this.h(a,"promoHtml",c?this.promoHtml:gfc_c);this.h(a,"insertHtml",function(a,b){gfc_wa(a,b)})};gfc_7[gfc_].Wk=function(a){return"blogger"==a};
gfc_7[gfc_].Lg=function(a,b,c,d){gfc_4m({id:a,text:b,version:this.Wk(this.hb.themeId)?1:gfc_c,style:c},d)};
gfc_7[gfc_].Q=function(a){function b(b,c){d.h(a,b,gfc_L(c,d))}this.h(a,"facesPerRow",this.Xb);for(var c in this.e)this.h(a,c,this.e[c]);var d=this;b("getThumbnail",this.zc);b("map",this.map);b("elide",gfc_wm);b("safeSlice",this.gi);b("showAllActivities",this.$u);b("transformActivity",this.kc);b("nextActivities",this.Nr);b("previousActivities",this.vs);b("showAllLinks",this.bv);b("transformLink",this.Nv);b("nextLinks",this.Rr);b("previousLinks",this.xs);b("showAllSites",this.ev);b("transformSite",
this.Ov);b("nextSites",this.Yr);b("previousSites",this.Ds);b("showAllMembers",this.cv);b("showBlockedMembers",this.gv);b("showUnblockedMembers",this.xv);b("nextMembers",this.Sr);b("nextBlockedMembers",this.Or);b("previousMembers",this.ys);b("previousBlockedMembers",this.ws);b("showAllProfileFriends",this.dv);b("nextProfileFriends",this.Xr);b("previousProfileFriends",this.Cs);b("showAllViewerFriends",this.fv);b("nextViewerFriends",this.Zr);b("previousViewerFriends",this.Es);b("isHome",this.wh);b("goBack",
this.$g);b("goBackToHome",this.qv);b("invite",this.invite);b("editSettings",this.Ab);b("signout",this.signout);b("signin",this.signin);b("viewProfile",this.en);b("blockUser",this.bj);b("unblockUser",this.Rv);b("goToInviteFriend",this.Sp);b("sendMessageDialog",this.xu);b("goToBlockMember",this.Rp);b("goToEditProfile",this.Ab);b("goToViewerProfile",this.Tp);b("sendInvite",this.wu);b("blockMember",this.Hn);b("acceptFriendRequest",this.on);b("ignoreFriendRequest",this.Iq);b("viewFriendRequests",this.Zv);
b("acceptAllFriendRequests",this.nn);b("numPreviewFriends",this.yp);b("numPreviewMembers",this.zp);b("showInvitedBy",this.Gp)};
gfc_7[gfc_].ok=function(a){var a=gfc_j.max(1,a?this.rc-1:this.rc),b=this.d[gfc_q].members?this.d[gfc_q].members[gfc_9a]():0,c=this.d[gfc_q].friends?this.d[gfc_q].friends[gfc_9a]():0,b=gfc_j[gfc_En](b/this.Xb),c=gfc_j[gfc_En](c/this.Xb);b>gfc_j[gfc_En](a/2)?c>gfc_j[gfc_nb](a/2)?(b=gfc_j[gfc_En](a/2),c=gfc_j[gfc_nb](a/2)):b=gfc_j.max(0,a-c):c>gfc_j[gfc_nb](a/2)&&(c=gfc_j.max(0,a-b));b*=this.Xb;c*=this.Xb;return a={numMembers:b,numFriends:c}};gfc_7[gfc_].zp=function(a){return this.ok(a).numMembers};
gfc_7[gfc_].yp=function(a){return this.ok(a).numFriends};gfc_7[gfc_].Qt=function(a,b){var c=gfc_h[gfc_G](),d={},e=gfc_h[gfc_x][gfc_qc];d[e.FILTER]="PUBLICLY_VISIBLE";d[e.FIRST]=b[gfc_C];d[e.MAX]=b.pageSize?b.pageSize:this.oa;var f=[gfc_h[gfc_t][gfc_H].ID,gfc_h[gfc_t][gfc_H][gfc_1a],gfc_h[gfc_t][gfc_H][gfc_Nc]];d[e[gfc_tc]]=f;d[gfc_h[gfc_x].DataRequestFields.ESCAPE_TYPE]=gfc_h.EscapeType.NONE;c.add(c[gfc_3b](gfc_1d(),d),"ownerFriends");c[gfc_B](a)};
gfc_7[gfc_].Ns=function(a){this.d[gfc_q].members=a.get("ownerFriends")[gfc_r]()};gfc_7[gfc_].Kt=function(a,b){var c=gfc_h[gfc_G](),d={},e=gfc_h[gfc_x][gfc_qc];d[e.FIRST]=b[gfc_C];d[e.MAX]=b.pageSize?b.pageSize:this.oa;d[gfc_h[gfc_x].DataRequestFields.ESCAPE_TYPE]=gfc_h.EscapeType.NONE;e={};e[gfc_h[gfc_Wa][gfc_H][gfc_Kb]]=gfc_h[gfc_Wa].PersonId.OWNER;e[gfc_h[gfc_Wa][gfc_H][gfc_pb]]="BLOCKED";e[gfc_h[gfc_Wa][gfc_H][gfc_0a]]=1;e=gfc_h[gfc_Wc](e);c.add(c[gfc_3b](e,d),"blockedMembers");c[gfc_B](a)};
gfc_7[gfc_].Js=function(a){this.d[gfc_q].blockedMembers=a.get("blockedMembers")[gfc_r]()};gfc_7[gfc_].Wt=function(a,b){var c=gfc_h[gfc_G](),d=b&&b.person&&b.person[gfc_z]()||this.v[gfc_D].person[gfc_z](),e={},f=gfc_h[gfc_x][gfc_qc];e[f.FIRST]=b[gfc_C];e[f.MAX]=b.pageSize?b.pageSize:this.oa;d=this.xl(d);e[gfc_h[gfc_x].DataRequestFields.ESCAPE_TYPE]=gfc_h.EscapeType.NONE;c.add(c[gfc_3b](d,e),"profileFriends");c[gfc_B](a)};
gfc_7[gfc_].xl=function(a){var b={};b[gfc_h[gfc_Wa][gfc_H][gfc_Kb]]=a;b[gfc_h[gfc_Wa][gfc_H][gfc_pb]]="FRIENDS";b[gfc_h[gfc_Wa][gfc_H][gfc_0a]]=1;return gfc_h[gfc_Wc](b)};gfc_7[gfc_].Ss=function(a){this.d[gfc_q][gfc_D].friends=a.get("profileFriends")[gfc_r]()};gfc_7[gfc_].Vi=function(a){for(var b=gfc_h[gfc_q].getDataContext(),c=0;c<a[gfc_m];c++){var d=a[c],d=b.getDataSet(d);if(!d||d.code)return gfc_d}return gfc_b};
gfc_7[gfc_].Rt=function(a){var b=this.oa,c=!b||24==b;c&&gfc_h[gfc_q]&&this.Vi(["ownerFriends","viewer","siteSettings","friendRequests"])?a(gfc_h[gfc_q].getDataContext()[gfc_r]()):(c=gfc_Dn.newBatch(),b={userId:"@owner",groupId:"@friends",count:b,filterBy:"PUBLICLY_VISIBLE"},c.add("ownerFriends",gfc_Dn.people.get(b)),c.add("viewer",gfc_Dn.people.getViewer()),c.add("siteSettings",gfc_Dn.extensions.get({command:"GetSiteSettings"})),c.add("friendRequests",gfc_Dn.extensions.get({command:"GetFriendRequests",
params:'{"idSpec" : "VIEWER"}'})),(b=gfc_la().psinvite)&&c.add("invitedBy",gfc_Dn.extensions.get({command:"DecodeInvitation",params:{token:b}})),c.execute(a))};gfc_7[gfc_].Os=function(a,b){this.d[gfc_q].members=gfc_Ud(a.ownerFriends,gfc_Pd);this.d[gfc_q].viewer=gfc_Pd(a.viewer);this.Nl(a,b,gfc_b);this.hb=a[gfc_uc];var c=gfc_la();if(c.psinvite&&(this.d[gfc_q].viewer==gfc_c||""==this.d[gfc_q].viewer))a.invitedBy&&(a.invitedBy.nickname=a.invitedBy.displayName),this.d[gfc_q].invitedBy=new gfc_h[gfc_t](a.invitedBy)};
gfc_7[gfc_].iu=function(a,b){var b=b||{},c=b.pageSize||this.maxFacesPerPage,d=!b[gfc_C]||0==b[gfc_C],e=!c||20==c;d&&e&&gfc_h[gfc_q]&&this.Vi(["friends","isViewerAdmin"])?a(gfc_h[gfc_q].getDataContext()[gfc_r]()):(d=gfc_Dn.newBatch(),c={userId:"@viewer",groupId:"@friends",count:c},b[gfc_C]&&(c.startIndex=b[gfc_C]),d.add("friends",gfc_Dn.people.get(c)),d.add("isViewerAdmin",gfc_Dn.people.get({userId:"@viewer",groupId:"ADMINS"})),d.execute(a))};
gfc_7[gfc_].Ys=function(a){var b=a.friends;b&&!b.error&&(this.d[gfc_q].friends=gfc_Ud(b,gfc_Pd));this.om(a)};gfc_7[gfc_].ju=function(a){var b=gfc_h[gfc_G]();b.add(gfc_Sd("VIEWER"),"numWaitingMessages");b[gfc_B](a)};gfc_7[gfc_].$s=function(a){this.numWaitingMessages=a.get("numWaitingMessages")[gfc_r]().numberOfWaitingMessages};
gfc_7[gfc_].Yt=function(a){this.log("requesting promo");var b=new gfc_e[gfc_Eb],b=b.getLang()+(b[gfc_lc]()?"_"+b[gfc_lc]():""),c=gfc_h[gfc_G]();c.add(gfc_Hd("GetPromo",{hl:b}),"promo");c[gfc_B](a)};gfc_7[gfc_].Us=function(a){this.log("processing promo");if((a=a.get("promo")[gfc_r]())&&-1!=a.promoCode)this.promoCode=a.promoCode,this.promoHtml=a.promoHtml};
gfc_7[gfc_].wn=function(){for(var a=function(){this.promoHtml=gfc_c;for(var a=gfc_9f("div","fc-promo-main",gfc_R("peg")),b=0;b<a[gfc_m];b++)gfc_1g(a[b],gfc_d);this.Y();this.log("Dismissing promo "+this.promoCode);a=gfc_h[gfc_G]();a.add(gfc_Hd("DismissPromo",{promoCode:this.promoCode}));a[gfc_B](gfc_L(function(){this.log("The promo has been dismissed");this.promoCode=-1},this))},b=gfc_9f("a","fc-promo-dismiss-link",gfc_R("peg")),c=0;c<b[gfc_m];c++){var d=b[c],e="click";gfc_Ph(d,e);gfc_Ih(d,e,gfc_L(a,
this))}};gfc_7[gfc_].om=function(a){var b=a.isViewerAdmin;if(b&&!b.error)this.d[gfc_q].isViewerAdmin=b.list[gfc_m];else if(a.get&&a.get("isViewerAdmin")&&(a=a.get("isViewerAdmin"))&&!a[gfc_Ab]())this.d[gfc_q].isViewerAdmin=a[gfc_r]()[gfc_9a]()};gfc_7[gfc_].nn=function(a){var b=[];a.each(function(a){a={user:a[gfc_I](goog.opensocial.peoplesense.Invite[gfc_H].INVITER)[gfc_z](),action:"ACCEPT"};b[gfc_l](a)});this.render(["sendFriendRequestResponse","members","viewerFriends"],gfc_L(this.sg,this),{friendRequestResponses:b})};
gfc_7[gfc_].qv=function(){this.fa();this.render(["members","viewerFriends"],"faces")};gfc_7[gfc_].on=function(a){a={user:a[gfc_z](),action:"ACCEPT"};this.render(["sendFriendRequestResponse","members","viewerFriends"],gfc_L(this.sg,this),{friendRequestResponses:[a]})};gfc_7[gfc_].Zv=function(){this.fa();this.B("friend-requests")};gfc_7[gfc_].en=function(a){this.Ib()?(this.fa(),this.aw(a)):gfc_Ed(a[gfc_z]())};
gfc_7[gfc_].aw=function(a){this.render(["profileData","profileFriends","activityData"],"profile",{person:a})};gfc_7[gfc_].du=function(a,b){var c=gfc_h[gfc_G](),d=gfc_h[gfc_x][gfc_qc],e={};e[d.FIRST]=b&&b[gfc_C]?b[gfc_C]:0;var f=this.d[gfc_q][gfc_D].person[gfc_z]();e[d.MAX]=this.Om;c.add(gfc_Zd(gfc_h[gfc_Wc]({userId:f}),e),"profileSites");c[gfc_B](a)};gfc_7[gfc_].Ws=function(a){this.d[gfc_q][gfc_D].sites=a.get("profileSites")[gfc_r]()};
gfc_7[gfc_].Vt=function(a,b){this.d[gfc_q].profile={};var b=b||{},c=b.person,d={},c=c[gfc_z](),e=gfc_h[gfc_G](),f=[gfc_h[gfc_t][gfc_H].ID,gfc_h[gfc_t][gfc_H][gfc_1a],gfc_h[gfc_t][gfc_H][gfc_Nc],gfc_h[gfc_t][gfc_H].ABOUT_ME,gfc_h[gfc_t][gfc_H].URLS,"profileExtensions"],g=gfc_h[gfc_x][gfc_qc];d[g[gfc_tc]]=f;d[gfc_h[gfc_x].DataRequestFields.ESCAPE_TYPE]=gfc_h.EscapeType.NONE;e.add(e.newFetchPersonRequest(c,d),"profile");e.add(e.newFetchPersonRequest("VIEWER",d),"viewer");e.add(gfc_Xd("VIEWER","ADMINS"),
"isViewerAdmin");e.add(e.newFetchPersonRequest("OWNER",d),"owner");this.hb||e.add(gfc_Rd(),"siteSettings");e.add(gfc_Xd(c,"ADMINS"),"isAdmin");e.add(gfc_Xd(c,"BLOCKED"),"isBlocked");this.isMessagingEnabled&&e.add(gfc_Sd(c),"canMessage");e[gfc_B](a)};
gfc_7[gfc_].Ff=function(a,b){var c=b.person[gfc_z](),d=gfc_h[gfc_Wc]({userId:c}),e=gfc_h[gfc_G]();(this.d[gfc_q].viewer&&c!=this.d[gfc_q].viewer[gfc_z]()||this.Ib())&&e.add(gfc_Wd(b.person[gfc_z](),"VIEWER"),"isProfileFriend");e.add(e[gfc_xb](d,{}),"activities");e[gfc_B](a)};
gfc_7[gfc_].ld=function(a,b){a.get("activities")[gfc_r]()!=gfc_c&&(this.d[gfc_q][gfc_D].activities=a.get("activities")[gfc_r]());var c=a.get("isProfileFriend");c&&b&&this.d[gfc_q].viewer!=gfc_c&&this.d[gfc_q].viewer[gfc_z]()!=b.person[gfc_z]()&&(this.d[gfc_q][gfc_D].isFriend=c[gfc_r]()[gfc_s])};
gfc_7[gfc_].Rs=function(a,b){var c=a.get("profile")[gfc_r]();this.d[gfc_q][gfc_D].person=c;this.d[gfc_q][gfc_D].person.externalProfileUrl=gfc_c;var d=c[gfc_I](gfc_h[gfc_t][gfc_H].URLS),e=[];if(d)for(var f=0;f<d[gfc_m];f++){var g=d[f];"profile"!=g[gfc_I](gfc_h.Url[gfc_H].TYPE)&&"externalProfile"!=g[gfc_I](gfc_h.Url[gfc_H].TYPE)&&e[gfc_l](g);"externalProfile"==g[gfc_I](gfc_h.Url[gfc_H].TYPE)&&(this.d[gfc_q][gfc_D].person.externalProfileUrl=g[gfc_I](gfc_h.Url[gfc_H].ADDRESS))}this.d[gfc_q][gfc_D].links=
new gfc_Hn(e,this.rf,0);this.d[gfc_q].owner=a.get("owner")[gfc_r]();this.d[gfc_q].viewer=a.get("viewer")[gfc_r]();if((d=this.d[gfc_q].viewer)&&b.person[gfc_z]()!=this.d[gfc_q].viewer[gfc_z]())this.d[gfc_q][gfc_D].isAdmin=a.get("isAdmin")[gfc_r](),this.d[gfc_q][gfc_D].isAdmin&&(this.d[gfc_q][gfc_D].isAdmin=this.d[gfc_q][gfc_D].isAdmin[gfc_9a]()),this.d[gfc_q][gfc_D].isBlocked=a.get("isBlocked")[gfc_r](),this.d[gfc_q][gfc_D].isBlocked&&(this.d[gfc_q][gfc_D].isBlocked=this.d[gfc_q][gfc_D].isBlocked[gfc_9a]());
c=c[gfc_I]("profileExtensions");c=this.Pb.kf(c,this.Pb.wi);d=[];for(f in c){e=c[f];g={};g.title=e.title;var h=gfc_d;if("SHORT_TEXT"==e.entryType||"LONG_TEXT"==e.entryType)e[gfc_s]&&e[gfc_s][gfc_bb]&&(g.body=[],g[gfc_Ob][gfc_l](e[gfc_s][gfc_bb]),h=gfc_b);else if(e[gfc_s]&&e[gfc_s].choice&&0<e[gfc_s].choice[gfc_m]){g.body=[];for(h=0;h<e[gfc_s].choice[gfc_m];++h)g[gfc_Ob][gfc_l](e[gfc_s].choice[h][gfc_Jc]);h=gfc_b}h&&d[gfc_l](g)}this.d[gfc_q][gfc_D].profileExtensions=d;this.hb||(this.hb=a.get("siteSettings")[gfc_r]());
this.isMessagingEnabled&&(f=(f=a.get("canMessage"))&&f[gfc_r]().canSendMessage,this.d[gfc_q][gfc_D].canSendMessage=f);this.om(a)};gfc_7[gfc_].bj=function(a){this.render(["blockUser"],"profile",{person:a})};gfc_7[gfc_].Rv=function(a){this.render(["unblockUser"],"profile",{person:a})};gfc_7[gfc_].map=function(a,b){var c=[],d=gfc_L(function(a,b,c){a[gfc_l](b(c))},this,c,b);a.each(d);return c};gfc_7[gfc_].cv=function(){this.fa();this.B("members-page")};
gfc_7[gfc_].gv=function(){this.fa();this.render(["blocked-member-page"],"blocked-members-page",{start:0})};gfc_7[gfc_].xv=function(){this.Fi()};gfc_7[gfc_].Sr=function(a){this.render(["member-page"],"members-page",{start:this.oa+a.getOffset()})};gfc_7[gfc_].ys=function(a){this.render(["member-page"],"members-page",{start:a.getOffset()-this.oa})};gfc_7[gfc_].Or=function(a){this.render(["blocked-member-page"],"blocked-members-page",{start:this.oa+a.getOffset()})};
gfc_7[gfc_].ws=function(a){this.render(["blocked-member-page"],"blocked-members-page",{start:a.getOffset()-this.oa})};gfc_7[gfc_].fv=function(){this.fa();this.B("viewer-friends-page")};gfc_7[gfc_].Zr=function(a){this.render(["viewerFriends"],"viewer-friends-page",{start:this.oa+a.getOffset()})};gfc_7[gfc_].Es=function(a){this.render(["viewerFriends"],"viewer-friends-page",{start:a.getOffset()-this.oa})};gfc_7[gfc_].dv=function(){this.fa();this.B("profile-friends-page")};
gfc_7[gfc_].Xr=function(a){this.render(["profile-friends-page"],"profile-friends-page",{start:this.oa+a.getOffset(),person:this.d[gfc_q][gfc_D].person})};gfc_7[gfc_].Cs=function(a){this.render(["profile-friends-page"],"profile-friends-page",{start:a.getOffset()-this.oa,person:this.d[gfc_q][gfc_D].person})};gfc_7[gfc_].bv=function(){this.fa();this.B("links")};gfc_7[gfc_].Rr=function(a){var b=this.rf+a.getOffset();this.d[gfc_q][gfc_D].links=new gfc_Hn(a.all(),this.rf,b);this.B("links")};
gfc_7[gfc_].xs=function(a){var b=a.getOffset()-this.rf;this.d[gfc_q][gfc_D].links=new gfc_Hn(a.all(),this.rf,b);this.B("links")};gfc_7[gfc_].ev=function(){this.fa();this.B("sites")};gfc_7[gfc_].Yr=function(a){this.render(["sitesData"],"sites",{start:this.Om+a.getOffset()})};gfc_7[gfc_].Ds=function(a){this.render(["sitesData"],"sites",{start:a.getOffset()-this.Om})};gfc_7[gfc_].$u=function(){this.fa();this.B("activities")};
gfc_7[gfc_].Nr=function(a){this.render(["activityData"],"activities",{start:this.Ba+a.getOffset()})};gfc_7[gfc_].vs=function(a){this.render(["activityData"],"activities",{start:a.getOffset()-this.Ba})};gfc_7[gfc_].Ze=function(a){this.render(["deleteActivity"],this.d[gfc_Pb],{activity:a})};gfc_7[gfc_].Jt=function(a,b){var c=gfc_h[gfc_G]();c.add(gfc_Yd(b.person[gfc_z](),["BLOCKED"],[]),"block");this.fd();c[gfc_B](a)};
gfc_7[gfc_].Is=function(a){if(a=!a.get("block")[gfc_Ab]())this.d[gfc_q][gfc_D].isBlocked=gfc_b};gfc_7[gfc_].gu=function(a,b){var c=gfc_h[gfc_G]();c.add(gfc_Yd(b.person[gfc_z](),[],["BLOCKED"]),"unblock");this.fd();c[gfc_B](a)};gfc_7[gfc_].Xs=function(a){if(a=!a.get("unblock")[gfc_Ab]())this.d[gfc_q][gfc_D].isBlocked=gfc_d};
gfc_7[gfc_].Gf=function(a,b){var c=b.activity,d=c[gfc_I](gfc_h[gfc_4b][gfc_H].ID),c=gfc_h[gfc_Wc]({userId:c[gfc_I](gfc_h[gfc_4b][gfc_H][gfc_Kb])}),e=gfc_h[gfc_G]();e.add(gfc_Id(d),"delete");e.add(e[gfc_xb](c,{}),"activities");e[gfc_B](a)};
gfc_7[gfc_].kc=function(a){var b=gfc_cn,c=function(a){return a=a[gfc_p](/<a/g,"<a target='_top'")},d=gfc_c,e=this.d[gfc_q].viewer;e!=gfc_c&&a[gfc_I](gfc_h[gfc_4b][gfc_H][gfc_Kb])==this.d[gfc_q].viewer[gfc_z]()&&(d=gfc_L(this.Ze,this,a));(e=a[gfc_I](gfc_h[gfc_4b][gfc_H].STREAM_FAVICON_URL,{escapeType:"none"}))||(e=gfc_g.friendconnect_imageUrl+"/favicons.gif");return{icon:e,time:b(gfc_ha(a[gfc_I](gfc_h[gfc_4b][gfc_H].POSTED_TIME))),link:a[gfc_I](gfc_h[gfc_4b][gfc_H].STREAM_URL,{escapeType:"none"}),
siteTitle:a[gfc_I](gfc_h[gfc_4b][gfc_H].STREAM_TITLE,{escapeType:"none"}),innerHTML:c(a[gfc_I](gfc_h[gfc_4b][gfc_H].TITLE,{escapeType:"none"})),body:c(a[gfc_I](gfc_h[gfc_4b][gfc_H].BODY,{escapeType:"none"})),deleteHandler:d}};gfc_7[gfc_].Ov=function(a){var b=gfc_e[gfc_oc].unescapeString,c=gfc_Fn;return{icon:c(a[gfc_I](gfc_h[gfc_t][gfc_H][gfc_bc])),link:a[gfc_I](gfc_h[gfc_t][gfc_H][gfc_bc]),title:b(a[gfc_Lb]())}};
gfc_7[gfc_].Nv=function(a){var b=gfc_e[gfc_oc].unescapeString,c=gfc_Fn,d=a[gfc_I](gfc_h.Url[gfc_H].ADDRESS);return{icon:c(d),link:d,title:b(a[gfc_I](gfc_h.Url[gfc_H].LINK_TEXT))||d}};gfc_7[gfc_].Xt=function(a,b){var c=gfc_h[gfc_G](),d=b.person[gfc_z](),e=gfc_h[gfc_x][gfc_qc],f=this.xl(d),g={};g[gfc_h[gfc_x].DataRequestFields.ESCAPE_TYPE]=gfc_h.EscapeType.NONE;c.add(c[gfc_3b](f,g),"friends");f={};f[e.FIRST]=this.Rw;f[e.MAX]=this.Qw;c.add(gfc_Zd(gfc_h[gfc_Wc]({userId:d}),f),"profileSites");c[gfc_B](a)};
gfc_7[gfc_].Iq=function(a){a={user:a[gfc_z](),action:"DENY"};this.render(["sendFriendRequestResponse","members","viewerFriends"],gfc_L(this.sg,this),{friendRequestResponses:[a]})};gfc_7[gfc_].sg=function(a){return a&&a["next-view"]?a["next-view"]:["friend-requests"]};gfc_7[gfc_].cu=function(a,b){var c=b[gfc_D],d=gfc_h[gfc_G]();d.add(gfc_Jd(c[gfc_z](),b[gfc_Ib]),"friendRequest");this.fd();d[gfc_B](a)};gfc_7[gfc_].Vs=function(a){a.get("friendRequest")[gfc_Ab]()||(this.d[gfc_q][gfc_D].isInvited=gfc_b)};
gfc_7[gfc_].Nt=function(a,b){var c=gfc_Dn.newBatch(),d=b.friendRequestResponses;c.add("updateFriendRequest",gfc_Dn.extensions.get({command:"ProcessFriendRequests",params:'{"requests":'+gfc_e[gfc_9b].stringify(d)+"}"}));c.add("friendRequests",gfc_Dn.extensions.get({command:"GetFriendRequests",params:'{"idSpec" : "VIEWER"}'}));this.fd();c.execute(a)};gfc_7[gfc_].Sp=function(){this.fa();this.B("invite-friend")};gfc_7[gfc_].xu=function(a){this.isMessagingEnabled&&(a=a[gfc_I](gfc_h[gfc_t][gfc_H].ID),this.yu(a))};
gfc_7[gfc_].yu=function(a){if(this.isMessagingEnabled){var a="/friendconnect/messaging/compose?recipientId="+a,b=570,c=395;gfc_Xm(a,""+b,""+c)}};gfc_1[gfc_].pn=function(){var a="/friendconnect/messaging/accept",b=570,c=375;gfc_Xm(a,""+b,""+c);return gfc_d};gfc_7[gfc_].Rp=function(){this.fa();this.B("block-member")};gfc_7[gfc_].Tp=function(){this.en(this.d[gfc_q].viewer)};
gfc_7[gfc_].wu=function(a){this.wf();var a={profile:a},b=gfc_R("inviteMessage");b&&(a.message=gfc_Qf(b));this.render(["sendFriendRequest"],"profile",a)};gfc_7[gfc_].Hn=function(a){this.wf();this.bj(a)};gfc_7[gfc_].Nl=function(a,b,c){c=c||gfc_d;this.d[gfc_q].friendRequests=gfc_Ud(a.friendRequests,gfc_Ld);b["next-view"]=0<this.d[gfc_q].friendRequests[gfc_9a]()?"friend-requests":"faces";c||gfc_Im("friend")};
gfc_7[gfc_].Ts=function(a){this.d[gfc_q][gfc_D].sites=a.get("profileSites")[gfc_r]();this.d[gfc_q][gfc_D].friends=a.get("friends")[gfc_r]()};gfc_7[gfc_].Gp=function(){return this.ov};gfc_7[gfc_].Y=function(){this.Aw.rebuild();this.wn();gfc_e[gfc_Ya].adjustHeight()};gfc_7[gfc_].ks=function(a){return a=gfc_S("span",{"class":"fc-cap-link-big"},gfc_S("a",{"class":"fc-cap-link-big"},this.e.MSG_OPTIONS),a.wg())};
gfc_7[gfc_].js=function(){var a=[];a[a[gfc_m]]=gfc_S("div",{"class":"goog-menuitem menuaction-settings"},this.e.MSG_SITE_SETTINGS);a[a[gfc_m]]=this.isSocialShareEnabled?gfc_S("div",{"class":"goog-menuitem menuaction-share"},this.e.MSG_MEMBERS_SHARE):gfc_S("div",{"class":"goog-menuitem menuaction-invite"},this.e.MSG_INVITE_FRIENDS);this.d[gfc_q].isViewerAdmin&&!this.Ib()&&(a[a[gfc_m]]=gfc_S("div",{"class":"goog-menuitem menuaction-manage"},this.e.MSG_MANAGE));a[a[gfc_m]]=gfc_S("div",{"class":"goog-menuitem menuaction-signout"},
this.hb.signOutPrompt||this.e.MSG_SIGN_OUT);a[a[gfc_m]]=gfc_S("div",{"class":"goog-menuseparator fc-menuseparator-line"});a[a[gfc_m]]=gfc_S("div",{"class":"goog-menuitem menuaction-aboutfc"},gfc_S("span",{"class":"fc-small-menu-link"},this.e.MSG_ABOUT_FC));return a};
gfc_7[gfc_].ls=function(a){a[gfc_vb]();a=a[gfc_Rb].g()[gfc_7a];a[gfc_Yb]("menuaction-settings")?this.Ab():a[gfc_Yb]("menuaction-invite")?this.invite():a[gfc_Yb]("menuaction-share")?this.share():a[gfc_Yb]("menuaction-signout")?this.signout():a[gfc_Yb]("menuaction-manage")?this.Yp():a[gfc_Yb]("menuaction-aboutfc")&&(a=gfc_g[gfc_2a](gfc_Pm()+"/friendconnect"),a[gfc_6b]())};gfc_7[gfc_].Yp=function(){var a={},b=gfc_e[gfc_n][gfc_ob]().canvas;gfc_Im("lightbox");gfc_e[gfc_n].requestNavigateTo(b,a);return gfc_d};
var gfc_Gn=function(a){for(var b={},c=0;c<a[gfc_m];++c)b[a[c]]=a[c];return b}("HEIGHT,BORDER_COLOR,CONTENT_BG_COLOR,CONTENT_HEADLINE_COLOR,CONTENT_LINK_COLOR,CONTENT_SECONDARY_TEXT_COLOR,CONTENT_SECONDARY_LINK_COLOR,CONTENT_TEXT_COLOR,ENDCAP_BG_COLOR,ENDCAP_LINK_COLOR,ENDCAP_TEXT_COLOR,FACE_SIZE,NUMBER_ROWS".split(","));
gfc_7[gfc_].s=function(){var a=gfc_Gn,b=[],c=0;this.f(a.HEIGHT);this.zh()&&(b[c++]=this.j(".fc-thumbnail img {height:%spx;width:%spx}",this.f(a.FACE_SIZE)));b[c++]=this.j(".fc-scroll-botnav, .fc-scroll, .fc-noscroll-botnav {height: %spx;}\n",this.km);b[c++]=this.j(".fc-members,.fc-members-canvas {border-color: %s;}\n.fc-userpage-itemlist,.fc-userpage-itemlist-canvas,.fc-botcap-short { border-top-color: %s; }\n.fc-topcap,.fc-topverb,.fc-friendreq,.fc-friendreqs,.fc-timeframe { border-bottom-color: %s; }\n",
this.f(a.BORDER_COLOR));this.hf()&&(this.Jk("profile")?b[c++]=".fc-topcap {height: "+this.slimTopCapHeight+"px;}\n":this.Ch()?b[c++]=".fc-topcap {height: 0px;}\n":b[c++]=".fc-topcap {height: "+this.tinyTopCapHeight+"px;}\n");this.Ib()?b[c++]=".fc-userpic-caption {margin-left: 59px;}\n":b[c++]=".fc-userpic-caption {margin-left: 40px;}\n";this.Ch()?b[c++]=".fc-topcap-color {background-color: white;}\n":b[c++]=this.j(".fc-topcap-color {background-color: %s;}\n",this.f(a.ENDCAP_BG_COLOR));this.Xk()?b[c++]=
".fc-botcap-short {background-color: white;}\n":b[c++]=this.j(".fc-botcap-short {background-color: %s;}\n",this.f(a.ENDCAP_BG_COLOR));b[c++]=this.j(".fc-botverb, .fc-topverb, .fc-members-header {background-color: %s;}\n",this.f(a.ENDCAP_BG_COLOR));b[c++]=this.j(".fc-botverb, .fc-topverb, .fc-members-header {background-color: %s;}\n",this.f(a.ENDCAP_BG_COLOR));b[c++]=this.j(".fc-topcap, .fc-botverb, .fc-topverb, .fc-botcap-short, .fc-header-sectitle, .fc-members-header {color: %s;}\n",this.f(a.ENDCAP_TEXT_COLOR));
b[c++]=this.j(".fc-botverb,.fc-topcap .fc-menutriangle-down, .fc-topcap .fc-menutriangle-up,.fc-topcap a, .fc-topcap a:active, .fc-topcap a:visited,.fc-topcap-link a, .fc-topcap-link a:active, .fc-topcap-link a:visited,.fc-cap-link-big a, .fc-cap-link-big a:active,.fc-left-verb a, .fc-left-verb a:active, .fc-left-verb a:visited,.fc-right-verb a, .fc-right-verb a:active, .fc-right-verb a:visited,.fc-subtle-botcap a, .fc-subtle-botcap a:active, .fc-subtle-botcap a:visited.fc-left-verb-canvas a, .fc-left-verb-canvas a:active, .fc-left-verb-canvas a:visited,.fc-right-verb-canvas a, .fc-right-verb-canvas a:active, .fc-right-verb-canvas a:visited {color: %s;}\n",
this.f(a.ENDCAP_LINK_COLOR));b[c++]=this.j(".fc-content-bg, .fc-subtle-botcap {background-color:%s;}\n",this.f(a.CONTENT_BG_COLOR));b[c++]=this.j(".fc-content a, .fc-content a:active, .fc-content a:visited,\n.fc-item-body a, .fc-item-body a:active, .fc-item-body a:visited,\n.fc-see-all a, .fc-see-all a:active, .fc-see-all a:visited,\n.fc-content-link a, .fc-content-link a:active, .fc-content-link a:visited,\n.fc-content-canvas a, .fc-content-canvas a:active, .fc-content-canvas a:visited {color: %s;}\n",
this.f(a.CONTENT_LINK_COLOR));b[c++]=this.j(".fc-members,.fc-members-canvas {color:%s;}\n",this.f(a.CONTENT_TEXT_COLOR));b[c++]=this.j(".fc-helpful,.fc-on-other-site,.fc-no-elements, .ot-activity-metadata {color:%s;}\n",this.f(a.CONTENT_SECONDARY_TEXT_COLOR));b[c++]=this.j(".fc-faded-link a, .fc-faded-link a:active, .fc-faded-link a:visited, .fc-faded-link-small a, .fc-faded-link-small a:active, .fc-faded-link-small a:visited {color: %s;}\n",this.f(a.CONTENT_SECONDARY_LINK_COLOR));b[c++]=this.j(".fc-sectitle {color: %s;}\n",
this.f(a.CONTENT_HEADLINE_COLOR));return gfc_7.i.s[gfc_A](this)+b[gfc_K]("\n")};gfc_M("goog.peoplesense.gadget.Members",gfc_7);gfc_M("goog.peoplesense.gadget.Members.start",gfc_7[gfc_C]);var gfc_Hn=function(a,b,c){gfc_h.Collection[gfc_A](this,a[gfc_gb](c,c+b),c,a[gfc_m]);this.gw=a;this.ea=b};gfc_Hn.inherits(gfc_h.Collection);gfc_Hn[gfc_].all=function(){return this.gw};gfc_Hn[gfc_].mb=function(){return this.ea};gfc_M("goog.peoplesense.gadget.Members.PagedCollection.prototype.all",gfc_Hn[gfc_].all);
gfc_M("goog.peoplesense.gadget.Members.PagedCollection.prototype.getPageSize",gfc_Hn[gfc_].mb);
